version: 3
endpoint: http://localhost:8080
admin_secret: hasura-dev-admin-secret
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://api:3000
